init

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,9 @@
 name: GitHub Actions Demo
 run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
 on: [push]
+env:
+  VER_TARGET: 560.94
+  BASEDIR: .
 jobs:
   Explore-GitHub-Actions:
     runs-on: ubuntu-20.04
@@ -15,13 +18,14 @@ jobs:
       options:
         --user root
     steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
+      - name: default info
+        run: |
+          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
+          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
+          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
       - name: Check out repository code
         uses: actions/checkout@v4
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
       - name: List files in the repository
         run: |
           ls ${{ github.workspace }}
@@ -33,36 +37,16 @@ jobs:
         run: |
           apt-get update
           ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
-          apt-get install aptitude wget curl sudo p7zip-full busybox bsdmainutils xxd xvfb ca-certificates -y --no-install-recommends
+          apt-get install wget curl sudo p7zip-full busybox bsdmainutils xxd xvfb ca-certificates -y --no-install-recommends
           sudo busybox --install
       - name: Install dotnet dependencies
         run: |
-          #wget --no-check-certificate https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh -O dotnet-install.sh
-          #chmod +x ./dotnet-install.sh
-          #sudo ./dotnet-install.sh --runtime dotnet --channel 9.0 --quality preview --install-dir /usr/share/dotnet
-          #echo 'export DOTNET_ROOT=/usr/share/dotnet' >> /etc/profileecho
-          #export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools' >> /etc/profile
-          #. /etc/profile
           wget --no-check-certificate https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
           dpkg -i packages-microsoft-prod.deb
           rm packages-microsoft-prod.deb
           apt-get update
           apt-get install -y dotnet-runtime-8.0
           dotnet --list-runtimes
-      - name: add wine keys
-        run: |
-          #sudo dpkg --add-architecture i386
-          #sudo mkdir -pm755 /etc/apt/keyrings
-          #sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
-          #sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/focal/winehq-focal.sources
-          #sudo apt-get update
-          echo "none"
-      - name: Install wine apt
-        run: |
-          #apt install --install-recommends winehq-stable winetricks -y -f
-          #Xvfb :0 -screen 0 1024x768x16 &
-          #export DISPLAY=:0.0
-          echo "none"
       - name: Install jsign
         run: |
           wget https://github.com/ebourg/jsign/releases/download/6.0/jsign_6.0_all.deb -O jsign_6.0_all.deb
@@ -71,10 +55,41 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install --install-recommends -y osslsigncode mscompress rename
+      - name: set env
+        run: |
+          env
+          DriverDir=${VER_TARGET}-desktop-win10-win11-64bit-international-dch-whql
+          echo "DriverDir=${DriverDir}" >> $GITHUB_ENV
+          echo "DisplayDriverDir=${BASEDIR}/${DriverDir}/Display.Driver" >> $GITHUB_ENV
+          echo "displaydriverDir=${BASEDIR}/${DriverDir}/display.driver" >> $GITHUB_ENV
+      - name: get env
+        run: |
+          env
+          echo $DisplayDriverDir
+      - name: Download Driver
+        run: |
+          curl "https://cn.download.nvidia.com/Windows/${VER_TARGET}/${DriverDir}.exe" -o ${DriverDir}.exe
+          [ -e "${DriverDir}.exe" ] || echo "nvidia windows driver installer not found"
+          md5sum ${DriverDir}.exe
+      - name: unpack driver
+        run: |
+          which 7z &>/dev/null || echo "have not install p7zip-full for 7z tool (http://p7zip.sourceforge.net/)"
+          echo "extracting the driver installer, please wait..."
+          7z x -o${DriverDir} "${DriverDir}.exe"
       - name: Install patch.sh
         run: |
           chmod +x patch.sh
           ./patch.sh
+      - name: gen and sign cat
+        run: |
+          mv ${DisplayDriverDir} ${displaydriverDir}
+          for i in $( find ${displaydriverDir} -maxdepth 1 -name "*[A-Z]*" ); do mv -if "$i" "`echo $i | tr 'A-Z' 'a-z'`"; done
+          for i in $( find ${displaydriverDir} -maxdepth 2 -name "*[A-Z]*" ); do mv -if "$i" "`echo $i | tr 'A-Z' 'a-z'`"; done
+          for i in $( find ${displaydriverDir} -maxdepth 3 -name "*[A-Z]*" ); do mv -if "$i" "`echo $i | tr 'A-Z' 'a-z'`"; done
+          for i in $( find ${displaydriverDir} -maxdepth 4 -name "*[A-Z]*" ); do mv -if "$i" "`echo $i | tr 'A-Z' 'a-z'`"; done
+          dotnet ${BASEDIR}/tools/inf2cat/Inf2Cat.exe /driver:"${displaydriverDir}" /os:10_x64 /verbose
+          mv ${displaydriverDir} ${DisplayDriverDir}
+          jsign --keystore tools/cert.pfx --storetype PKCS12 --storepass GreenDamTan --tsaurl http://timestamp.digicert.com ${DisplayDriverDir}/nv_disp.cat
       - name: Upload artifact
         uses: actions/upload-artifact@master
         with:
